project:
  type: website
  output-dir: docs

website:
  title: "Ben Baur"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: about.html
        text: About
      - href: projects.html
        text: Projects
      - href: exploration.html
        text: Exploration
    background: "dark"
    primary: "teal"

format:
  html:
    theme: cosmo
    css: styles.css