project:
  type: website
  output-dir: docs

website:
  title: "Ben Baur"
  navbar:
    left:
      - href: about.html
        text: About
      - href: projects.html
        text: Projects
    background: "dark"  # Navbar color
    primary: "teal"     # Highlight color

format:
  html:
    theme: cosmo        
    css: styles.css